#!/bin/sh

echo ENVIRONMENT=TEST >> .env
echo DOCKER_HUB_ACCESS_TOKEN=$DOCKER_HUB_ACCESS_TOKEN >> .env
echo DOCKER_HUB_USERNAME=$DOCKER_HUB_USERNAME >> .env
echo DOCKER_ORGANIZATION=$DOCKER_ORGANIZATION>> .env
echo DOCKER_APP=$DOCKER_APP >> .env
echo CIRCLE_SHA1=$CIRCLE_SHA1 >> .env
echo API_PORT=$API_PORT >> .env
echo DB_CONNECTION_STRING=$MONGO_DB_CONNECTION_STRING >> .env